---
- name:  Deploy app
  hosts: tag_reddit-app-{{ env }}
  # hosts: tag_reddit-app-stage
  gather_facts: true
  become: true
  tags: nginx

  tasks:
    - include_role:
        name: deploy
    - include_role:
        name: jdauphant.nginx
      when: "env != 'local'"

